In [46]:
import pandas as pd
df = pd.read_pickle('cleaned_two.pkl')
df.head()

,age,primary_diagnosis,insurance_type,discharge_disposition,label,prev_readmit_group,comorbidities_group,los_group,medications_group,followup_visits_group,risk_score_bin
0,66,Diabetes,Medicare,Home Health,1,1,five or more,6 to 8,8 to 14,5 or more,7
1,55,Diabetes,Private,Home Health,1,2,four,6 to 8,6,4,7
2,69,Hypertension,Medicare,Skilled Nursing,1,2,five or more,6 to 8,8 to 14,5 or more,7
3,83,Stroke,Medicare,Skilled Nursing,1,2,five or more,9+,8 to 14,4,7
4,54,Stroke,Uninsured,Home Health,1,1,four,9+,6,2,6

In [47]:
df.groupby('discharge_disposition')['label'].agg(['count', 'mean'])

                       count      mean
discharge_disposition
Home                     317  0.340694
Home Health             6065  0.758450
Rehab                     50  0.340000
Skilled Nursing         1568  0.929847

In [48]:
df['dc_location'] = df['discharge_disposition']
df['dc_location'] = df['dc_location'].replace({
    'Home': 'Home/Rehab',
    'Rehab': 'Home/Rehab'
})

In [49]:
df['dc_location'].value_counts()

dc_location
Home Health        6065
Skilled Nursing    1568
Home/Rehab          367
Name: count, dtype: int64

In [50]:
df.groupby('primary_diagnosis')['label'].agg(['count', 'mean'])

                   count      mean
primary_diagnosis
Appendicitis         534  0.711610
COPD                 952  0.868697
Diabetes            1470  0.705442
Fracture             434  0.702765
Heart Failure        403  0.858561
Hypertension        1301  0.696387
Influenza            233  0.686695
Kidney Disease       868  0.832949
Pneumonia            425  0.738824
Sepsis               497  0.869215
Stroke               883  0.852775

In [51]:
# primary dx tiers:
means = df.groupby('primary_diagnosis')['label'].mean()
def tier(mean):
    if mean <= .75:
        return 'lower'
    else:
        return 'higher'

df['primary_dx_tier'] = df['primary_diagnosis'].map(means).apply(tier)

In [52]:
df['primary_dx_tier'].value_counts()

primary_dx_tier
lower     4397
higher    3603
Name: count, dtype: int64

In [53]:
df2 = df.copy()
df2 = df2.drop(columns=['primary_diagnosis'])

In [54]:
df2.to_pickle('cleaned_three.pkl')