In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df = pd.read_pickle('coef_clean_two.pkl')

In [10]:
df.head()

,insurance_type,label,prev_readmit_group,los_group,risk_score_bin,dc_location,primary_dx_tier,age_bin
0,Medicare/Medicaid,1,1,6 to 8,7,HH/SNF,lower,2.0
1,Private,1,2,6 to 8,7,HH/SNF,lower,2.0
2,Medicare/Medicaid,1,2,6 to 8,7,HH/SNF,lower,3.0
3,Medicare/Medicaid,1,2,9+,7,HH/SNF,higher,3.0
4,Uninsured,1,1,9+,6,HH/SNF,higher,2.0

In [11]:
df.sample(n=10)

,insurance_type,label,prev_readmit_group,los_group,risk_score_bin,dc_location,primary_dx_tier,age_bin
522,Medicare/Medicaid,0,1,6 to 8,3,HH/SNF,lower,1.0
5031,Medicare/Medicaid,1,2,9+,7,HH/SNF,lower,3.0
4338,Private,1,2,6 to 8,6,HH/SNF,higher,1.0
170,Uninsured,1,1,6 to 8,3,HH/SNF,lower,1.0
5473,Private,0,1,5 or less,2,HH/SNF,lower,1.0
4512,Medicare/Medicaid,1,2,6 to 8,7,HH/SNF,higher,1.0
1795,Medicare/Medicaid,0,1,6 to 8,2,HH/SNF,lower,1.0
7220,Medicare/Medicaid,1,2,9+,7,HH/SNF,higher,3.0
4543,Medicare/Medicaid,0,1,6 to 8,2,HH/SNF,lower,1.0
1943,Private,1,2,6 to 8,7,HH/SNF,higher,2.0